version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: msa-study-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: msa_study
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
